"""Cria tabelas de inventory (Entidade, Categoria e Item)

Revision ID: 9fc48e64ae53
Revises: dd2f6f4bd475
Create Date: 2025-05-12 12:05:20.958870

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc48e64ae53'
down_revision = 'dd2f6f4bd475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'categorias',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=50), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['parent_id'],
            ['categorias.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'entidades',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'item',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('codigo', sa.String(length=20), nullable=False),
        sa.Column('codigo_barra', sa.String(length=50), nullable=True),
        sa.Column('nome', sa.String(length=100), nullable=False),
        sa.Column('descricao', sa.String(length=255), nullable=True),
        sa.Column('imagem_url', sa.String(length=255), nullable=True),
        sa.Column('unidade', sa.String(length=5), nullable=True),
        sa.Column('peso', sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column(
            'comprimento', sa.Numeric(precision=10, scale=3), nullable=True
        ),
        sa.Column('largura', sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column(
            'profundidade', sa.Numeric(precision=10, scale=3), nullable=True
        ),
        sa.Column('entidade_id', sa.Integer(), nullable=True),
        sa.Column('categoria_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['categoria_id'],
            ['categorias.id'],
        ),
        sa.ForeignKeyConstraint(
            ['entidade_id'],
            ['entidades.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('codigo'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_table('entidades')
    op.drop_table('categorias')
    # ### end Alembic commands ###
