"""empty message

Revision ID: dd2f6f4bd475
Revises: 0b4920c396f3
Create Date: 2025-05-12 01:27:35.339912

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd2f6f4bd475'
down_revision = '0b4920c396f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'clientes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=150), nullable=False),
        sa.Column('email', sa.String(length=120), nullable=False),
        sa.Column('telefone', sa.String(length=20), nullable=True),
        sa.Column('endereco', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
    )
    op.create_table(
        'produtos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=150), nullable=True),
        sa.Column('descricao', sa.Text(), nullable=True),
        sa.Column(
            'preco_unitaro', sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column('sku', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('sku'),
    )
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=120), nullable=False),
        sa.Column('password_hash', sa.String(length=120), nullable=False),
        sa.Column('role', sa.String(length=120), nullable=False),
        sa.Column(
            'criado_em',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('password_hash'),
        sa.UniqueConstraint('role'),
    )
    op.create_table(
        'estoque',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('quantidade_disponivel', sa.Integer(), nullable=False),
        sa.Column('produto_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['produto_id'],
            ['produtos.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('produto_id'),
    )
    op.create_table(
        'pedidos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'data',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('status', sa.String(length=30), nullable=False),
        sa.Column('cliente_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['cliente_id'],
            ['clientes.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'itens_pedido',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('quantidade', sa.Integer(), nullable=False),
        sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('pedido_id', sa.Integer(), nullable=False),
        sa.Column('produto_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['pedido_id'],
            ['pedidos.id'],
        ),
        sa.ForeignKeyConstraint(
            ['produto_id'],
            ['produtos.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_pedido')
    op.drop_table('pedidos')
    op.drop_table('estoque')
    op.drop_table('users')
    op.drop_table('produtos')
    op.drop_table('clientes')
    # ### end Alembic commands ###
