"""Cria tabela associativa item_categoria e configura relacionamento muitos-para-muitos entre Item e Categoria

Revision ID: f631fa0e58b0
Revises: 9fc48e64ae53
Create Date: 2025-05-15 03:56:06.644104

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f631fa0e58b0'
down_revision = '9fc48e64ae53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'itens',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('codigo', sa.String(length=20), nullable=False),
        sa.Column('codigo_barra', sa.String(length=50), nullable=True),
        sa.Column('nome', sa.String(length=100), nullable=False),
        sa.Column('descricao', sa.String(length=255), nullable=True),
        sa.Column('imagem_url', sa.String(length=255), nullable=True),
        sa.Column('unidade', sa.String(length=5), nullable=True),
        sa.Column('peso', sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column(
            'comprimento', sa.Numeric(precision=10, scale=3), nullable=True
        ),
        sa.Column('largura', sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column(
            'profundidade', sa.Numeric(precision=10, scale=3), nullable=True
        ),
        sa.Column('entidade_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['entidade_id'],
            ['entidades.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('codigo'),
    )
    op.create_table(
        'item_categoria',
        sa.Column('item_id', sa.Integer(), nullable=False),
        sa.Column('categoria_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['categoria_id'],
            ['categorias.id'],
        ),
        sa.ForeignKeyConstraint(
            ['item_id'],
            ['itens.id'],
        ),
        sa.PrimaryKeyConstraint('item_id', 'categoria_id'),
    )
    op.drop_table('item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'item',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            'codigo',
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'codigo_barra',
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            'descricao',
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'imagem_url',
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'unidade', sa.VARCHAR(length=5), autoincrement=False, nullable=True
        ),
        sa.Column(
            'peso',
            sa.NUMERIC(precision=10, scale=3),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'comprimento',
            sa.NUMERIC(precision=10, scale=3),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'largura',
            sa.NUMERIC(precision=10, scale=3),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'profundidade',
            sa.NUMERIC(precision=10, scale=3),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'entidade_id', sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            'categoria_id', sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['categoria_id'], ['categorias.id'], name='item_categoria_id_fkey'
        ),
        sa.ForeignKeyConstraint(
            ['entidade_id'], ['entidades.id'], name='item_entidade_id_fkey'
        ),
        sa.PrimaryKeyConstraint('id', name='item_pkey'),
        sa.UniqueConstraint('codigo', name='item_codigo_key'),
    )
    op.drop_table('item_categoria')
    op.drop_table('itens')
    # ### end Alembic commands ###
